name: Deploy to Production

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: cd moebot
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd moebot
          host: ${{ secrets.HOST }}
          username: hk
          privateKey: ${{ secrets.PRIVATE_KEY}}

      - name: git pull
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: git pull
          host: ${{ secrets.HOST }}
          username: hk
          privateKey: ${{ secrets.PRIVATE_KEY}}
