name: Deploy to Production

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd moebot
            gg git pull
          host: ${{ secrets.HOST }}
          username: hk
          privateKey: ${{ secrets.PRIVATE_KEY}}
